### ISSUE TITLE
The newest release of the Crowd plugin (2.1.2) doesn’t work with SonarQube 7.9 LTS 

### ISSUE THREAD

**Issue by shivendrakd** [deepy/sonar-crowd#27] opened 2019-07-05 10:52 UTC
The newest release of the Crowd plugin (2.1.2) doesn’t work with SonarQube 7.9 LTS 

Please advise what we should do now.

**Comment by deepy** [comment] 2019-07-05 12:10
Duplicate of #25

**Closed by deepy** 2019-07-05 12:10 UTC
